repos:
-   repo: https://github.com/python-poetry/poetry
    rev: '1.8.4'
    hooks:
    -   id: poetry-check
    -   id: poetry-lock
-   repo: https://github.com/astral-sh/ruff-pre-commit
    rev: v0.8.1
    hooks:
    -   id: ruff
        args: [ --fix ]
    -   id: ruff-format
-   repo: https://github.com/RobertCraigie/pyright-python
    rev: v1.1.389
    hooks:
    -   id: pyright
